# Generated by Django 5.2.13 on 2026-05-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=200)),
                ('dob', models.CharField(max_length=50)),
                ('image', models.URLField()),
                ('about', models.TextField()),
                ('is_top', models.BooleanField(default=False)),
                ('short_about', models.CharField(max_length=50)),
            ],
        ),
    ]
