# Generated by Django 5.2.13 on 2026-05-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='artist_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
