# Generated by Django 5.2.13 on 2026-05-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_dimensions_product_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Metal', 'Metal'), ('Terracotta', 'Terracotta'), ('Photography', 'Photography'), ('Glass Art', 'Glass Art'), ('Premium', 'Premium'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
